services:
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB_NAME}
    volumes:
      - ./docker-postgresql/:/var/lib/postgresql/data
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - "5432:5432"
  api:
    image: marwanhawari/node-ts-express-postgresql
    restart: unless-stopped
    environment:
      PSQL_URI: "postgresql://${PSQL_USER}:${PSQL_PASS}@psql:5432/${PSQL_DB_NAME}"
    ports:
      - "5050:5050"
    depends_on:
      - psql

